$ANSIBLE_VAULT;1.1;AES256
34316162613439376462316161656434656466633835643038633534353161313963616466633136
3138376163303262383831386633303839313765623761390a333830626363663466623639363032
65353461666339356665613432346635336637626261356539346230333162653133656363356536
6163663437633036620a383531643331303437303939653263306133363036353430356165386262
62336536393235373462383236656361623761643433356566386537333637613136623137303838
34316237393963386336366636373764323036383538653864353566353637353134316634376135
65313962343063373561336164346364336463386563346664373138613538313035373265303864
36393737383163313638623333633937663566343639383262646162656235323337356561323964
33376337653265663133383237353361363038626639663561646235363566343565343136303365
3835303136616165656339636462383434323430356566623862
