$ANSIBLE_VAULT;1.1;AES256
34393938396237666537323034363139616438333837376665393564643461643265643737356164
3661373463323936326164386561323861333062343363630a653637643136393863663031353062
36333135323931636664666432626433393332653566646362316464353333323335623030666561
3262343639633565390a306333623033303433326166356136656266613638633565623861623433
64616463393230643261353731653631316362363139316139643461346435626534336439363832
32353666636134613464613036353530666438323630633031353836366236333438623266616365
62333462383637353361313861653561363761373838306632633563393261313439303636333239
63303538303039623232396137353966396534333561363962613139366335313535333636663861
65656432623165383336666262396362326434363562316232336464643339396463643439643865
38306337323731376632306132666563646666656132373435383236386230343635636137333831
63393266383861366439613130636537353064303064373133323938376533333139363366663764
61386262343435366234
