$ANSIBLE_VAULT;1.1;AES256
61633031393235353935333866323230646263373831646365396261386239666664356163643232
6637646661616266396565316232393664613461346537390a343530376136626237653331663035
63356133363037613236356134323463363966383233323631643466643931393464643461643433
3630663132363233640a663433313862666264613935636235303531313165376139343961333661
62326366373633363533313364653835303564306165376461376635376165656233
