$ANSIBLE_VAULT;1.1;AES256
35353338386132343335306661373665383936653362373834343166313330343135663764313430
3734623133346462333664663962633637356336316532390a646333323433633633316330326235
63353563396335663139323063623636373736626231323161613630343964633735316265656538
6331636461376564610a396334653564306230306231353932393033333334343334363061613532
39353035383962303635666566343864643739623964336332353132323063383432343736343066
64616136663639333662633832663437373462376632393839623866316161356462326161323630
33303131623933656364326663323832633630393136326432616635383837356635346263643864
33663433303035366463
